---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  flake8
  ansible-lint .
platforms:
  - name: ubuntu-18.04
    image: solita/ubuntu-systemd:18.04
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
